### PR TITLE
feat: add rule for preventing uncontrolled values

### PR DESCRIPTION
**Pull request by dolby360**
An attacker can call his repository with a malicious command and even steal GITHUB_TOKEN, Depending on the running context of the workflow.

### CODE REVIEW

**Comment by dolby360** [comment]
See more details here 
https://blog.gitguardian.com/github-actions-security-cheat-sheet/

**Comment by dimabru** [comment]
The rule description suggests that the rule should take care of all uncontrolled values available in github.
In reality, this rule identifies only one uncontrolled value - the title of a pr.

Maybe we should either add more cases to the rule or change its description to better describe what is does

@dolby360 WDYT?

**Comment by dolby360** [comment]
@dimabru you mean something like this regex?
```js
.*\${{github\.event\.(pull_request\.title|actor\.(id|login|display_login)|org.login)}}.*
```

**Comment by dimabru** [comment]
@dolby360 yeah, much better :)

**Review by dimabru — APPROVED** [review]

**Pull request merged**
